name: Auto-Merge Knowl Docs
description: Auto-Merge Knowl Docs
inputs:
  KNOWL_API_KEY:
    description: KNOWL_API_KEY
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment 
      run: |  
        echo "REPO_NAME=${{ github.event.repository.name }}" >> ${GITHUB_ENV}
        echo "OWNER_NAME=${{ github.repository_owner }}" >> ${GITHUB_ENV}
        echo "KNOWL_BACKEND_HTTP=https://staging-api.knowl.io/" >> ${GITHUB_ENV}
        echo "BRANCH_NAME=${{ github.head_ref }}" >> ${GITHUB_ENV}
        echo "${{ github.action_path }}" >> "$GITHUB_PATH"
      shell: bash
    - name: Prepare script file
      run: chmod +x "${{ github.action_path }}/run-gen-docs.sh"
      shell: bash
    - name: Run the script file
      run: run-gen-docs.sh ${{ github.workspace }}
      shell: bash
      env:
        KNOWL_API_KEY: ${{inputs.KNOWL_API_KEY}}
